name: Sync to Target Repo

on:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Target Repo
        env:
          PAT: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          git push --mirror https://adityaaditiya:${PAT}@github.com/adityaaditiya/coba1.git